services:
  postgres:
    image: postgres:latest
    container_name: semanticDB
    environment:
      POSTGRES_DB: semanticDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securePassword
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./localTempDB.csv:/docker-entrypoint-initdb.d/localTempDB.csv
    networks:
      - my-network
  node:
    image: semantic/node
    container_name: semanticNode
    build:
      context: ../
      dockerfile: ./docker/node.dockerfile
    network_mode: "host"
    environment:
      TERM: xterm
      PUPPETEER_EXECUTABLE_PATH: /app/puppeteer/chrome/linux-119.0.6045.105/chrome-linux64/chrome
    volumes:
      - ./texts:/app/texts
  ranking:
    image: semantic/ranking
    container_name: ranking
    build:
      context: ../
      dockerfile: ./docker/ranking.dockerfile
    volumes:
      - ./texts:/app/texts

networks:
  my-network:


